[versions]
multikulti = "2.0.4"

[libraries]
multikulti-datagen = { group = "com.possible-triangle", name = "multikulti-1.21.1-datagen-neoforge", version.ref = "multikulti" }

jei = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version = "19.21.0.247" }

oreganized = { "group" = "dev.galena", name = "oreganized-1.21.1", version = "5.3.0" }